name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Source Repository
        uses: actions/checkout@v2

      - name: Cache NPM dependencies
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: npm-${{ hashFiles('**/*.lock') }}
          restore-keys: |
            npm-

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14' # Choose the Node.js version you need

      - name: Install Dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Create Zip Archive
        run: |
          cd dist
          zip -r ../FRM-WebUI.zip .

      - name: Deploy to FicsitRemoteMonitoring Repository
        uses: actions/upload-artifact@v2
        with:
          name: deploy-artifact
          path: FRM-WebUI.zip

      - name: Checkout FicsitRemoteMonitoring Repository
        uses: actions/checkout@v2
        with:
          repository: GalaxyVOID/FicsitRemoteMonitoring
          ref: main
          path: ficsit-remote-monitoring
        env: 
          GITHUB_TOKEN: ${{ secrets.PAT_OTHER_REPO }}

      - name: Set Git Config
        run: |
          git config user.email ${{ secrets.EMAIL }}
          git config user.name ${{ secrets.USERNAME }}

      - name: Remove Existing Contents in www Folder
        run: |
          cd ficsit-remote-monitoring/www
          rm -rf ./*  # This command will remove all files and directories within www
          
      - name: Unzip and Replace Contents
        run: |
          cd ficsit-remote-monitoring
          unzip -oq ../FRM-WebUI.zip -d www
