name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Source Repository
        uses: actions/checkout@v2
        env: 
          GITHUB_TOKEN: ${{ secrets.PAT }}

      - name: Cache NPM dependencies
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: npm-${{ hashFiles('**/*.lock') }}
          restore-keys: |
            npm-

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14' # Choose the Node.js version you need

      - name: Install Dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Create Zip Archive
        run: |
          cd dist
          zip -r ../FRM-WebUI.zip .

      - name: Deploy to FicsitRemoteMonitoring Repository
        uses: actions/upload-artifact@v2
        with:
          name: FRM-WebUI
          path: FRM-WebUI.zip
          
      - name: Checkout Target Repository
        uses: actions/checkout@v2
        with:
          repository: GalaxyVOID/FicsitRemoteMonitoring

      - name: Download Zip File
        uses: actions/download-artifact@v2
        with:
          name: FRM-WebUI

      - name: Unzip Contents
        run: |
          unzip FRM-WebUI.zip -d tmp
          rm FRM-WebUI.zip

      - name: Replace www Folder Contents
        run: |
          ls
          rm -rf www
          mv tmp/* www
          rm tmp
