name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Source Repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14' # Choose the Node.js version you need

      - name: Install Dependencies and Build
        run: |
          npm install
          npm run build

      - name: Create Zip Archive
        run: |
          cd dist
          zip -r ../FRM-WebUI.zip .

      - name: Deploy to FicsitRemoteMonitoring Repository
        uses: actions/upload-artifact@v2
        with:
          name: deploy-artifact
          path: FRM-WebUI.zip

      - name: Checkout FicsitRemoteMonitoring Repository
        uses: actions/checkout@v2
        with:
          repository: GalaxyVOID/FicsitRemoteMonitoring
          ref: main
          path: ficsit-remote-monitoring

      - name: Unzip and Replace Contents
        run: |
          cd ficsit-remote-monitoring/www
          unzip -o ../../deploy-artifact
