name: Build WebUI

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install Bun
        run: |
          curl -fsSL https://bun.sh/install | bash
          echo "$HOME/.bun/bin" >> $GITHUB_PATH

      - name: Cache Bun & Next.js
        uses: actions/cache@v4
        with:
          path: |
            ~/.bun/install/cache
            ${{ github.workspace }}/.next/cache
          key: ${{ runner.os }}-nextjs-${{ hashFiles('**/bun.lockb') }}-${{ hashFiles('**/*.ts', '**/*.tsx') }}
          restore-keys: |
            ${{ runner.os }}-nextjs-${{ hashFiles('**/bun.lockb') }}-

      - name: Disable Next.js telemetry
        run: bunx next telemetry disable

      - name: Install dependencies
        run: bun install

      - name: Handle versioning
        run: |
          set -x
          BRANCH="${GITHUB_REF##*/}"
          echo "Running on branch: $BRANCH"
          
          if [ "$BRANCH" = "dev" ]; then
            BASE_VERSION=$(jq -r '.version' package.json | cut -d '-' -f1)
            SHORT_SHA=$(git rev-parse --short HEAD)
            DEV_VERSION="${BASE_VERSION}-${SHORT_SHA}"
            jq --arg v "$DEV_VERSION" '.version=$v' package.json > tmp.json && mv tmp.json package.json
            echo "Dev build version set to $DEV_VERSION"

          elif [ "$BRANCH" = "main" ]; then
            git config user.name "github-actions[bot]"
            git config user.email "github-actions[bot]@users.noreply.github.com"

            echo "Git status before release:"
            git status
            echo "Last commit before release:"
            git log -1 --oneline

            bunx release

            echo "Git status after release:"
            git status
            echo "Last commit after release:"
            git log -1 --oneline

            git push origin main --quiet
            git push origin --tags --quiet
          fi

      - name: Build project
        run: bun run build

      - name: Rename output folder
        run: mv ./out ./www

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: www
          path: ./www
