name: Close Linked Issues via Checkbox

on:
  issues:
    types: [edited]

jobs:
  close_issues:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v7
        with:
          script: |
            const issueBody = context.payload.issue.body;
            const prevBody = context.payload.changes?.body?.from;

            if (!prevBody) return;

            const closedLines = issueBody
              .split('\n')
              .filter((line, index) =>
                line.startsWith('- [x]') && prevBody.split('\n')[index]?.startsWith('- [ ]')
              );

            for (const line of closedLines) {
              const match = line.match(/#(\d+)/);
              if (match) {
                const issueNumber = parseInt(match[1], 10);
                await github.rest.issues.update({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  issue_number: issueNumber,
                  state: 'closed'
                });
                console.log(`Closed issue #${issueNumber}`);
              }
            }
